development:
  adapter: postgresql
  database: talaarawan_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: talaarawan_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: talaarawan_production
  pool: 5
  timeout: 5000
